# Generated by Django 5.1.3 on 2024-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_userprofile_managers_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='twitter_post',
            new_name='post_summary',
        ),
        migrations.RemoveField(
            model_name='article',
            name='word_count',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('inprogress', 'in progress'), ('published', 'published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.tag'),
        ),
    ]
