FROM python:3.12-bullseye

WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

CMD ["streamlit", "run", "uememparser/uememparser.py", "--server.port=8501", "--server.address=0.0.0.0"]
