# Generated by Django 5.1.3 on 2024-11-20 18:49

from django.db import migrations
from django.utils import timezone


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists():
        return

    superuser = User.objects.create_superuser(username="superadmin",
                                              email="example@example.com",
                                              password="superadmin",
                                              last_login=timezone.now()
                                              )
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
