# Generated by Django 5.1.3 on 2024-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliopiece_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopiece',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_thumbs/'),
        ),
    ]
