# Generated by Django 5.1.3 on 2024-12-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliopiece_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='portfolio_media/')),
                ('caption', models.CharField(max_length=150)),
                ('portfolio_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_elements', to='portfolio.portfoliopiece')),
            ],
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('portfolio_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_elements', to='portfolio.portfoliopiece')),
            ],
        ),
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='portfolio_media/')),
                ('caption', models.CharField(max_length=150)),
                ('portfolio_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_elements', to='portfolio.portfoliopiece')),
            ],
        ),
    ]
