# Generated by Django 5.1.3 on 2024-12-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_imageelement_textelement_videoelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMediaElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_media/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio_media/')),
                ('text', models.TextField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('portfolio_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='portfolio.portfoliopiece')),
            ],
        ),
    ]
