# Generated by Django 5.1.3 on 2024-12-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfoliomediaelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='portfolio_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_elements', to='portfolio.portfoliopiece'),
        ),
    ]
