# Generated by Django 5.1.3 on 2024-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_imageelement_portfolio_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
