# Generated by Django 5.1.3 on 2025-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_imageelement_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='caption',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
