# Generated by Django 5.1.3 on 2025-01-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_imageelement_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageelement',
            name='temp',
        ),
    ]
